# Generated by Django 3.1 on 2020-08-29 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greylistphrase',
            name='qset_threshold',
            field=models.IntegerField(default=60),
        ),
        migrations.CreateModel(
            name='SubscriberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='scrap metal', max_length=50)),
                ('pickup_range', models.IntegerField(default=8, verbose_name='Pickup Range (miles)')),
                ('is_available_for_pickup', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='blacklistword',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriberprofile'),
        ),
        migrations.AlterField(
            model_name='greylistphrase',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriberprofile'),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
