# Generated by Django 3.1 on 2020-08-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stdout', models.TextField()),
            ],
        ),
    ]
