# Generated by Django 3.1 on 2020-08-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_cronscrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('successful', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('stdout', models.TextField()),
                ('scrap_type', models.CharField(max_length=50, verbose_name='Scrape Type (Check-in-prompted, or cron)')),
            ],
        ),
        migrations.DeleteModel(
            name='CronScrape',
        ),
        migrations.RemoveField(
            model_name='scraplisting',
            name='location',
        ),
        migrations.AddField(
            model_name='scraplisting',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraplisting',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
